name: giphyapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  shared_preferences: ^2.2.3
  http: ^1.2.2
  connectivity_plus: ^2.2.1
  logger: ^1.1.0
  lottie: ^1.2.2
  #SVG Image
  flutter_svg: ^2.0.7
  image_picker: ^1.0.0
  file_picker: ^5.0.1
  flutter_cache_manager: ^3.3.1
  app_settings: ^5.1.1
  firebase_core: ^3.1.0
  #firebase messaging
  firebase_messaging: ^15.0.0


dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

