name: giphyapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  http: ^1.2.2
  logger: ^1.1.0
  lottie: ^3.1.2
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.0
  firebase_auth:
  cloud_firestore: ^5.0.0
  intl:
  flutter_localizations:
    sdk: flutter
  async:
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  shimmer: ^3.0.0
  cached_network_image:
  animated_text_kit:
  url_launcher:
  google_sign_in:

dev_dependencies:
  injectable_generator: ^2.4.4
  build_runner: ^2.3.0
  flutter_native_splash:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/app_logo.png
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/

flutter_intl:
  enabled: true
