// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSJfp4-AKpESx66P9EUq3DlkL09bKPnzs',
    appId: '1:837496800290:web:fc50aff31efed32eeef67b',
    messagingSenderId: '837496800290',
    projectId: 'giphyapp-ce239',
    authDomain: 'giphyapp-ce239.firebaseapp.com',
    storageBucket: 'giphyapp-ce239.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvwi8lreD6oVnhIg8YAe_vNw2rJUxQfRM',
    appId: '1:837496800290:android:06030253129ae761eef67b',
    messagingSenderId: '837496800290',
    projectId: 'giphyapp-ce239',
    storageBucket: 'giphyapp-ce239.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB95Ih1PheM69yeyG8Xn94KCv_Eyc7K_RI',
    appId: '1:837496800290:ios:44b72bf90fc84057eef67b',
    messagingSenderId: '837496800290',
    projectId: 'giphyapp-ce239',
    storageBucket: 'giphyapp-ce239.appspot.com',
    iosBundleId: 'com.giphyapp.giphyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB95Ih1PheM69yeyG8Xn94KCv_Eyc7K_RI',
    appId: '1:837496800290:ios:44b72bf90fc84057eef67b',
    messagingSenderId: '837496800290',
    projectId: 'giphyapp-ce239',
    storageBucket: 'giphyapp-ce239.appspot.com',
    iosBundleId: 'com.giphyapp.giphyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSJfp4-AKpESx66P9EUq3DlkL09bKPnzs',
    appId: '1:837496800290:web:4babcd367624923eeef67b',
    messagingSenderId: '837496800290',
    projectId: 'giphyapp-ce239',
    authDomain: 'giphyapp-ce239.firebaseapp.com',
    storageBucket: 'giphyapp-ce239.appspot.com',
  );
}
