name: giphy version

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: GiphyApp-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app 1:837496800290:android:06030253129ae761eef67b \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --groups testers \
            --release-notes "Automated build from GitHub Actions"

